import json
import logging

from aroviq.core.exceptions import SecurityException
from aroviq.core.llm import LLMProvider
from aroviq.engine.runner import AroviqEngine, EngineConfig
from aroviq.integrations import guard

# Configure logging to see what's happening
logging.basicConfig(level=logging.INFO, format='%(levelname)s: %(message)s')

class ShellGuardLLM(LLMProvider):
    """
    A simple mock LLM that acts as a security scanner for shell commands.
    It inspects the JSON structure of the Step generated by the decorator.
    """
    def generate(self, prompt: str, temperature: float = 0.0) -> str:
        # In a real scenario, the prompt contains the Step serialization.
        # Since this is a test, we simply assume the prompt contains the dangerous patterns we are looking for.

        # Check for dangerous patterns in the input args
        if "rm -rf /" in prompt:
             return json.dumps({
                "approved": False,
                "reason": "Detected high-risk command 'rm -rf /'. Entire system deletion prevented.",
                "risk_score": 1.0,
                "suggested_correction": "Please specify a specific directory or use a safer deletion method.",
                "source": "ShellGuardLLM"
            })

        return json.dumps({
            "approved": True,
            "reason": "Command appears safe.",
            "risk_score": 0.0,
            "source": "ShellGuardLLM"
        })

# Initialize Engine
llm = ShellGuardLLM()
config = EngineConfig(llm_provider=llm, risk_threshold=0.5, freeze_registry=False)
security_engine = AroviqEngine(config=config)

# IMPORTANT: By default, AroviqEngine only runs LogicVerifier (LLM) on THOUGHT steps.
# For this demo, we want to run the LLM-based check on ACTION steps too.
from aroviq.core.models import StepType
from aroviq.core.models import AgentContext

security_engine.registry.register(security_engine.logic_verifier, [StepType.ACTION])
security_engine.registry.freeze()

# --- The Protected Tool ---

@guard(engine=security_engine)
def run_shell_command(command: str, sudo: bool = False, context: AgentContext | None = None) -> str:
    """
    Executes a shell command. 
    This function is intercepted by Aroviq BEFORE it runs.
    """
    prefix = "sudo " if sudo else ""
    logging.info(f"EXECUTING: {prefix}{command}")
    return f"Success: {prefix}{command}"

# --- Demo Execution ---

def main() -> None:
    print("=== 🛡️  Aroviq Tool Guard Demo 🛡️  ===\n")

    # 1. Safe Command
    print("1. Attempting Safe Command: 'ls -la'")
    try:
        context = AgentContext(user_goal="List directory", current_state_snapshot={}, history=[])
        result = run_shell_command("ls -la", context=context)
        print(f"   Result: {result}\n")
    except SecurityException as e:
        print(f"   BLOCKED: {e}\n")

    # 2. Dangerous Command
    print("2. Attempting Dangerous Command: 'rm -rf /'")
    try:
        context = AgentContext(user_goal="Delete", current_state_snapshot={}, history=[])
        run_shell_command("rm -rf /", sudo=True, context=context)
        print("   Result: Success (This should not happen!)\n")
    except SecurityException as e:
        print("   🛑 BLOCKED BY AROVIQ")
        if e.verdict:
            print(f"   Reason: {e.verdict.reason}")
            print(f"   Risk Score: {e.verdict.risk_score}")
            print(f"   Source: {e.verdict.source}\n")
        else:
             print("   Reason: Blocked without verdict.\n")

if __name__ == "__main__":
    main()
