"""
Tier 1 Grounding Verifier.

Performs lightweight *structural* and *consistency* checks on OBSERVATION steps.
This is **not** a factual grounding system — it cannot verify whether tool
output is truthful, accurate, or actually came from the claimed tool.  What it
can do:

    - Reject empty or oversized observations
    - Detect known LLM confabulation phrases that indicate the observation was
      generated by a language model rather than returned by a real tool
    - Flag self-contradictory pairs within a short text window (heuristic;
      will produce false positives on naturally contradictory observations)
    - Detect a narrow set of implausible numeric constants
    - Enforce required output keys when a schema is supplied in metadata

The confabulation-marker and contradiction-pair checks are heuristics.  They
are calibrated to be useful as a *first filter* on common failure modes, not
as a substitute for genuine factual verification (which would require a
separate LLM call or a retrieval-augmented check against ground-truth data).
"""

from __future__ import annotations

import re
from typing import Any

from aroviq.core.models import AgentContext, Step, Verdict

# ---------------------------------------------------------------------------
# Heuristic rule sets
# ---------------------------------------------------------------------------

# Phrases that frequently appear in hallucinated / confabulated outputs.
_CONFABULATION_MARKERS: tuple[str, ...] = (
    "as an ai language model, i",
    "i don't have access to real-time",
    "i cannot browse the internet",
    "hypothetically speaking",
    "let's assume for the sake of argument",
    "i'll make up",
    "i'll fabricate",
    "pretend that",
)

# Pairs of contradictory substrings that should not both appear in the same
# short observation window (checked within a 300-char sliding window).
_CONTRADICTION_PAIRS: tuple[tuple[str, str], ...] = (
    ("succeeded", "failed"),
    ("success", "error"),
    ("completed", "did not complete"),
    ("found", "not found"),
    ("exists", "does not exist"),
    ("true", "false"),
    ("enabled", "disabled"),
    ("connected", "disconnected"),
)

# Implausible numeric patterns that suggest hallucination.
_IMPLAUSIBLE_YEAR = re.compile(r"\b(9999|0000|1111|2222|3333|4444|5555|6666|7777|8888)\b")

_MAX_OBSERVATION_CHARS = 16_000
_CONTRADICTION_WINDOW = 300


class GroundingVerifier:
    """
    Tier 1 offline grounding verifier for OBSERVATION steps.

    Applies lightweight structural and consistency checks only.  It does **not**
    verify factual accuracy or confirm that output actually came from the claimed
    tool — that would require a full retrieval-augmented or LLM-based grounding
    check, which is outside the scope of this verifier.

    Checks performed (in order):
    1. Non-empty, within size limit.
    2. Known LLM confabulation phrases (heuristic keyword match).
    3. Contradictory assertion pairs within a 300-char sliding window (heuristic;
       expect false positives on legitimately contradictory content).
    4. Implausible numeric constants.
    5. Required-key schema validation (only when metadata provides a schema).
    """

    @property
    def tier(self) -> int:
        return 1

    def name(self) -> str:
        return "grounding_verifier"

    def verify(self, step: Step, context: AgentContext) -> Verdict:
        text = self._stringify(step.content)

        if not text.strip():
            return Verdict(
                approved=False,
                reason="Observation content is empty.",
                risk_score=1.0,
                source="tier1:grounding_verifier",
                tier=1,
            )

        if len(text) > _MAX_OBSERVATION_CHARS:
            return Verdict(
                approved=False,
                reason="Observation content exceeds maximum allowed size.",
                risk_score=0.9,
                source="tier1:grounding_verifier",
                tier=1,
            )

        lowered = text.casefold()

        # Check for confabulation markers
        for marker in _CONFABULATION_MARKERS:
            if marker in lowered:
                return Verdict(
                    approved=False,
                    reason=(
                        f"Confabulation marker detected: '{marker}'. "
                        "Observation appears to be LLM-generated rather than a real tool output."
                    ),
                    risk_score=0.95,
                    suggested_correction="Ensure the OBSERVATION contains actual tool output, not LLM-generated text.",
                    source="tier1:grounding_verifier",
                    tier=1,
                )

        # Check for contradictory assertion pairs within sliding windows
        contradiction = self._find_contradiction(lowered)
        if contradiction:
            a, b = contradiction
            return Verdict(
                approved=False,
                reason=f"Self-contradictory observation: '{a}' and '{b}' appear in the same context.",
                risk_score=0.85,
                suggested_correction="Ensure the observation reports a single, consistent outcome.",
                source="tier1:grounding_verifier",
                tier=1,
            )

        # Check for implausible numeric constants
        if _IMPLAUSIBLE_YEAR.search(text):
            return Verdict(
                approved=False,
                reason="Observation contains implausible numeric constant (possible hallucination).",
                risk_score=0.75,
                suggested_correction="Verify the observation reflects actual tool output values.",
                source="tier1:grounding_verifier",
                tier=1,
            )

        # Schema-based structure check
        schema = step.metadata.get("expected_output_schema")
        if schema and isinstance(schema, dict):
            schema_verdict = self._check_schema(step.content, schema)
            if schema_verdict is not None:
                return schema_verdict

        return Verdict(
            approved=True,
            reason="Observation passed grounding checks.",
            risk_score=0.0,
            source="tier1:grounding_verifier",
            tier=1,
        )

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _find_contradiction(self, text: str) -> tuple[str, str] | None:
        for a, b in _CONTRADICTION_PAIRS:
            pos_a = text.find(a)
            if pos_a == -1:
                continue
            # Search for b within a window around a
            window_start = max(0, pos_a - _CONTRADICTION_WINDOW)
            window_end = min(len(text), pos_a + len(a) + _CONTRADICTION_WINDOW)
            window = text[window_start:window_end]
            if b in window:
                return (a, b)
        return None

    def _check_schema(self, content: Any, schema: dict) -> Verdict | None:
        """Validate that content (if dict) satisfies a simple required-keys schema."""
        if not isinstance(content, dict):
            return Verdict(
                approved=False,
                reason=f"Observation expected a dict output per schema, got {type(content).__name__}.",
                risk_score=0.8,
                source="tier1:grounding_verifier",
                tier=1,
            )
        required = schema.get("required", [])
        missing = [k for k in required if k not in content]
        if missing:
            return Verdict(
                approved=False,
                reason=f"Observation missing required output keys: {missing}.",
                risk_score=0.8,
                suggested_correction=f"Ensure the tool result includes keys: {required}.",
                source="tier1:grounding_verifier",
                tier=1,
            )
        return None

    def _stringify(self, content: Any) -> str:
        if isinstance(content, str):
            return content
        if isinstance(content, (dict, list)):
            try:
                import json
                return json.dumps(content, ensure_ascii=False, separators=(",", ":"))
            except (TypeError, ValueError):
                return str(content)
        return str(content)
